# python_helpers/doc_utils.py
import os, json
from jinja2 import Template

DOC_TEMPLATE = """
# {{ repo_name }}

## Overview
{{ summary or "No README found." }}

## File tree
{% for f in file_tree %}
- `{{ f }}`
{% endfor %}

## Top discovered symbols
{% for item in ccg_meta %}
### {{ item.file }}
- symbols: {{ item.num_symbols }}
- sample: {{ item.top_symbols }}
{% endfor %}

---

*Generated by DocGenie*
"""

def render_markdown(repo_name: str, summary: str, ccg_meta: list, file_tree: list, repo_path: str, output_base="./outputs"):
    repo_dir = os.path.join(output_base, repo_name)
    os.makedirs(repo_dir, exist_ok=True)
    path = os.path.join(repo_dir, "docs.md")
    tpl = Template(DOC_TEMPLATE)
    content = tpl.render(repo_name=repo_name, summary=summary, ccg_meta=ccg_meta, file_tree=file_tree)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    # Optionally add a small index.json with metadata
    meta = {"repo": repo_name, "path": path, "files": len(file_tree)}
    with open(os.path.join(repo_dir, "index.json"), "w", encoding="utf-8") as mfh:
        json.dump(meta, mfh, indent=2)
    return {"ok": True, "path": path, "outputs": {"doc_dir": repo_dir}}
